version: "3.8"

services:
  mongo:
    image: mongo
    restart: always
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodbdata:/data/db
        
  rabbitmq:
    image: rabbitmq:management
    restart: always
    container_name: rabbitmq
    ports:
      - 5672:5672   
      - 15672:15672 #for management
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    hostname: rabbitmq

# ports: from launchSettings.json:  "applicationUrl": "https://localhost:7270;http://localhost:5143" 
  products:
    container_name: productapp
    image: productapp
    build:
      context: .
      dockerfile: Products/Dockerfile
    ports:
      - 5143:80
      - 7270:443
    links:
      - mongo
      - rabbitmq
    depends_on:
      - mongo
      - rabbitmq
    volumes:
      - ./cert.pem:/app/cert  # Mount the directory containing your certificate files

volumes:
  mongodbdata:
  rabbitmqdata:
