version: "3.8"

services:
  mongo:
    image: mongo:1.0.0
    restart: always
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodbdata:/data/db


  rabbitmq:
    image: rabbitmq:management
    restart: always
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672 #for management
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    hostname: rabbitmq


  products:
    container_name: productapp
    image: productapp:1.0.0
    build:
      context: .
      dockerfile: Products/Dockerfile
    ports:
      - 5143:80
      - 7270:443
        #ports: from launchSettings.json:  "applicationUrl": "https://localhost:7270;http://localhost:5143" 
    links:
      - mongo
      - rabbitmq
    depends_on:
      - mongo
      - rabbitmq


  orders:
    container_name: ordersapp:1.0.0
    image: ordersapp
    build:
      context: .
      dockerfile: Orders/Dockerfile
    ports:
      - 5006:80
      - 7131:443
        #ports: from launchSettings.json:  "applicationUrl": "https://localhost:7270;http://localhost:5143" 
    links:
      - mongo
      - rabbitmq
    depends_on:
      - mongo
      - rabbitmq      


  members:
    container_name: membersapp:1.0.0
    image: membersapp
    build:
      context: .
      dockerfile: Members/Dockerfile
    ports:
      - 5057:80
      - 7052:443
        #ports: from launchSettings.json:  "applicationUrl": "https://localhost:7270;http://localhost:5143" 
    links:
      - mongo
      - rabbitmq
    depends_on:
      - mongo
      - rabbitmq

volumes:
  mongodbdata:
  rabbitmqdata:
